name: Update Copyright Year

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 1 *'  # Runs at midnight on January 1st every year

jobs:
  update-year:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update copyright year
        run: |
          current_year=$(date +'%Y')
          sed -i "s/Copyright [0-9]\{4\}/Copyright $current_year/" README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update copyright year to $current_year"
          git push
