name: Update Copyright Year

on:
  schedule:
    # Run this job at 00:00 on the 1st of January every year
    - cron: '0 0 1 1 *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Copyright Year
        run: |
          # Get current year
          CURRENT_YEAR=$(date +"%Y")

          # Replace old year in README.md with the new one
          sed -i "s/©️ [0-9]\{4\}/©️ $CURRENT_YEAR/" README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update copyright year to $CURRENT_YEAR"
          git push
